name: Deploy Javadoc
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/wrapper-validation-action@v1

      - name: Verify Gradlew
        run: chmod +x gradlew
      - name: Generate Javadocs
        run: ./gradlew javadoc --stacktrace
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: .

