name: Deploy Javadoc
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: gradle/wrapper-validation-action@v1
      - name: Generate Javadocs
        run: ./gradlew documentation javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: .

